### ISSUE TITLE
[BUG] Error when the user is not  authenticated 

### ISSUE THREAD

**Issue by hermannleboss** [globe-and-citizen/Celebrity-Fanalyzer#266] opened 2023-07-09 11:30 UTC
**Describe the bug**
There is some log error when the user store is loaded.

**To Reproduce**

1. Go to '/'
2. Then display the inspector

**Screenshots**
![image](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/28951070/0346c407-5bb3-4d02-a2b0-ad1fd19df4b6)

When i comment some parts of the code there is no error again. 
![image](https://github.com/globe-and-citizen/Celebrity-Fanalyzer/assets/28951070/e2210596-adef-4f04-9a62-5f9bac8ea5cb)

**Comment by arnonrdp** [comment] 2023-07-11 18:40
@hermannleboss, perhaps this issue was resolved with some of the commits I made recently.
I am unable to reproduce here.
Could you check?

**Closed** 2023-07-17 08:18 UTC
Labels: bug, intermediate
